#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckupBO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	public partial class entityBODataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public entityBODataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public entityBODataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public entityBODataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public entityBODataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Patients> Patients
		{
			get
			{
				return this.GetTable<Patients>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class Patients
	{
		
		private int _tpr_id;
		
		private string _hn_no;
		
		private string _en_no;
		
		private string _fullName;
		
		public Patients()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tpr_id")]
		public int tpr_id
		{
			get
			{
				return this._tpr_id;
			}
			set
			{
				if ((this._tpr_id != value))
				{
					this._tpr_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hn_no", CanBeNull=false)]
		public string hn_no
		{
			get
			{
				return this._hn_no;
			}
			set
			{
				if ((this._hn_no != value))
				{
					this._hn_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_en_no", CanBeNull=false)]
		public string en_no
		{
			get
			{
				return this._en_no;
			}
			set
			{
				if ((this._en_no != value))
				{
					this._en_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullName", CanBeNull=false)]
		public string fullName
		{
			get
			{
				return this._fullName;
			}
			set
			{
				if ((this._fullName != value))
				{
					this._fullName = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
