//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallDataTakeCareArrived.WS_Trakcare {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_Trakcare.WS_GetDataBytrakSoap")]
    public interface WS_GetDataBytrakSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetvitalSign", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetvitalSign(string strEn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetvitalSignPreviouseDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetvitalSignPreviouseDate(string HN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFrequence", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetFrequence();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPharmacyItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPharmacyItem(string strItemCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVitalSignBefor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetVitalSignBefor(string StrHn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListPatientOfday", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListPatientOfday(string strToday);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListPatientByEpisode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListPatientByEpisode(string strEn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListEpisodeByHn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ListEpisodeByHn(string strHn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLocation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLocation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDoctorDmPathway", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDoctorDmPathway();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOtherLocationDoctors", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOtherLocationDoctors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListItem(string strHn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLastEpi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getLastEpi(string strHn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListIemOPD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListIemOPD(int strENRowid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListIemIPD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListIemIPD(int strENRowid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCareproviderCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCareproviderCode(string strUsrCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getUser(string strUsrCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTop5Diagnosis", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetTop5Diagnosis(string strHN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDiagnosis", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDiagnosis(string HN, string DoctorUserID, string BeginDate, string EndDate, string EN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDiagnosisByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDiagnosisByDate(string strHN, string strBeginDate, string strEndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMedicineByEn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetMedicineByEn(string strHN, string strEn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDiagnosisByEn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDiagnosisByEn(string strHN, string strEn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDiagnosisByEnAll", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDiagnosisByEnAll(string strHN, string strEn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTop5Medicine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetTop5Medicine(string strHN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMedicineByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetMedicineByDate(string strHN, string strBeginDate, string strEndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTop5NextAppointment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetTop5NextAppointment(string strHN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAppointmentByHN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAppointmentByHN(string strHN, string isHPC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCheckupLab", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCheckupLab(string strHn, string strFrom, string strTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetXrayResultList_XrayResult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetXrayResultList_XrayResult(string PMINo, string OrdSttDateFrom, string OrdSttDateTo, string ADMRowId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListCurrentMedByEN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListCurrentMedByEN(string strEN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemForThreeVisit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetItemForThreeVisit(string strHn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMedicineByHN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetMedicineByHN(string strHN, string BeginDate, string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListMed", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListMed(string CodeOrDesc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDiagForSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDiagForSave(string strHN, string strEn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPTByHN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getPTByHN(string strHN, string AdmDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getManualHN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getManualHN(string strHN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListPayor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListPayor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllergen", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getAllergen(string Input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOnWard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetOnWard(string Todate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPayorbyEN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPayorbyEN(string EN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getOnWardByDoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getOnWardByDoc(string Todate, string DocCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPatientByEpiRowID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getPatientByEpiRowID(string EpiRowID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getORRequestOT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getORRequestOT(string RequestDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getORAnaestMethod", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getORAnaestMethod(string CodeDesc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getORAnestTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getORAnestTime(string AnaestNo, string EN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getOrderByHnSubCat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getOrderByHnSubCat(string HN, string SubCatCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getOrderByEN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getOrderByEN(string EN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogonTrakcare", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable LogonTrakcare(string UserID, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVitalSignByHN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetVitalSignByHN(string HN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getVitalSignByHN_EN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getVitalSignByHN_EN(string HN, string EN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLastEN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetLastEN(string HN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPTDemographic", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPTDemographic(string HN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetVaccineByHN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetVaccineByHN(string strHN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPharItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPharItem(string ARCIM_Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBrestPatientByHN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetBrestPatientByHN(string HN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPTAppointment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPTAppointment(string HPCSite, string AppDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPTArrived", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPTArrived(string HPCSite, string AppDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPTArrivedCheckUp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPTArrivedCheckUp(string HPCSite, string AppDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPTArrivedCheckUpFilter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPTArrivedCheckUpFilter(string HPCSite, string EN, string AppDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPTOrderByLocDateHn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPTOrderByLocDateHn(string HPCSite, string OrderDate, string HN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllOrderSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllOrderSet(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllOrderItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllOrderItem(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllICD10", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllICD10(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllICD9", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllICD9(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPTPackage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPTPackage(int EN_RowId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllergyByHN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllergyByHN(string HN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllAllergyByHN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllAllergyByHN(string HN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllAllergyByHN_NameDob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAllAllergyByHN_NameDob(string HN, string name, string dob_yyyyMMdd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetItemByOrserSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetItemByOrserSet(int OrderSetId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLocationByType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetLocationByType(string LocType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetQuestionnaireHPC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetQuestionnaireHPC(string HN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCareprovider", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCareprovider(string Input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetORCareprovider", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetORCareprovider(string Input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetORAnaestCareprovider", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetORAnaestCareprovider(string Input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getApptByHN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getApptByHN(string HN, string Location, string ApptDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListCityArea", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListCityArea(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListCity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListCity(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListProvince", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListProvince(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListAddress(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOperationByHN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetOperationByHN(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMedicineByDoctor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetMedicineByDoctor(string strHN, string strEn, string DocCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOtherAddress", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetOtherAddress(string HN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDiagnosisByDoctor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDiagnosisByDoctor(string strHN, string strEn, string DocCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListPaymentAgreement", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListPaymentAgreement(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListPlan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListPlan(string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetXrayResult", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetXrayResult(string strHN, string BeginDate, string EndDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPharDrugForm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPharDrugForm(string PHCD_Code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAdmitHistory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAdmitHistory(string HN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProcedureByHN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetProcedureByHN(string HN, string DateFrom, string DateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContactPerson", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetContactPerson(string HN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDischargeDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDischargeDate(string EN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetManualLab", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetManualLab(string strHn, string strFrom, string strTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/findDiagnosis", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string findDiagnosis(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/findMedication", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string findMedication(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDrug", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetDrug(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEPIRowIDByEN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetEPIRowIDByEN(string EN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPTImageByHN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPTImageByHN(string HN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBannerByHN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetBannerByHN(string HN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get4PathwayPTInfoByEN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable Get4PathwayPTInfoByEN(string Admdate, string EN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPTInfoByHN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPTInfoByHN(string HN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPTInfoByEN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPTInfoByEN(string EN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStartToEndEpisodeByEN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetStartToEndEpisodeByEN(string EN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConsultLocationByEN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetConsultLocationByEN(string EN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOTRequestDoneBySurgeryDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetOTRequestDoneBySurgeryDate(string SurgeryDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentRoomByEN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCurrentRoomByEN(string EN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWardRoomBedMovementByEN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetWardRoomBedMovementByEN(string EN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentENByHN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetCurrentENByHN(string HN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListOperationByHN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ListOperationByHN(string HN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAdmissionAppointmentByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAdmissionAppointmentByDate(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderItemByDesc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetOrderItemByDesc(string Desc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBillSubByDesc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetBillSubByDesc(string Desc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBillGroupByDesc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetBillGroupByDesc(string Desc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderSetOrderItemByDesc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetOrderSetOrderItemByDesc(string Desc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderDetailByOrderRowID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetOrderDetailByOrderRowID(string RowID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLabByHNLabCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetLabByHNLabCode(string HN, string LabCode, string LabSet, int Rank);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPTArrivedIncaseFlatFileNotGen", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPTArrivedIncaseFlatFileNotGen(string ArrDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStockItemFromTrak", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetStockItemFromTrak(string strKeyWord);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLogonAD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetLogonAD(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAuditEPR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAuditEPR(string hn, string dateFrom, string dateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAuditDocView", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetAuditDocView(string hn, string dateFrom, string dateTo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetORSEquipmentImplant", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetORSEquipmentImplant();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBDMSNexEntel_Data", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetBDMSNexEntel_Data(string hn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPatientAdmissionByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPatientAdmissionByDate(string Dateyyy_mm_dd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderAdmissionByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetOrderAdmissionByDate(string Dateyyy_mm_dd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDischargeInfoByFinalDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDischargeInfoByFinalDate(string FinalDateyyy_mm_dd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetConsultMedicine", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetConsultMedicine(string Dateyyy_mm_dd, string OrderCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPhamacyReview", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetPhamacyReview(string PrescNo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_GetDataBytrakSoapChannel : CallDataTakeCareArrived.WS_Trakcare.WS_GetDataBytrakSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_GetDataBytrakSoapClient : System.ServiceModel.ClientBase<CallDataTakeCareArrived.WS_Trakcare.WS_GetDataBytrakSoap>, CallDataTakeCareArrived.WS_Trakcare.WS_GetDataBytrakSoap {
        
        public WS_GetDataBytrakSoapClient() {
        }
        
        public WS_GetDataBytrakSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_GetDataBytrakSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_GetDataBytrakSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_GetDataBytrakSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetvitalSign(string strEn) {
            return base.Channel.GetvitalSign(strEn);
        }
        
        public System.Data.DataSet GetvitalSignPreviouseDate(string HN) {
            return base.Channel.GetvitalSignPreviouseDate(HN);
        }
        
        public System.Data.DataSet GetFrequence() {
            return base.Channel.GetFrequence();
        }
        
        public System.Data.DataSet GetPharmacyItem(string strItemCode) {
            return base.Channel.GetPharmacyItem(strItemCode);
        }
        
        public System.Data.DataTable GetVitalSignBefor(string StrHn) {
            return base.Channel.GetVitalSignBefor(StrHn);
        }
        
        public System.Data.DataSet ListPatientOfday(string strToday) {
            return base.Channel.ListPatientOfday(strToday);
        }
        
        public System.Data.DataSet ListPatientByEpisode(string strEn) {
            return base.Channel.ListPatientByEpisode(strEn);
        }
        
        public System.Data.DataSet ListEpisodeByHn(string strHn) {
            return base.Channel.ListEpisodeByHn(strHn);
        }
        
        public System.Data.DataSet GetLocation() {
            return base.Channel.GetLocation();
        }
        
        public System.Data.DataSet GetDoctorDmPathway() {
            return base.Channel.GetDoctorDmPathway();
        }
        
        public System.Data.DataSet GetOtherLocationDoctors() {
            return base.Channel.GetOtherLocationDoctors();
        }
        
        public System.Data.DataTable ListItem(string strHn) {
            return base.Channel.ListItem(strHn);
        }
        
        public System.Data.DataTable getLastEpi(string strHn) {
            return base.Channel.getLastEpi(strHn);
        }
        
        public System.Data.DataTable ListIemOPD(int strENRowid) {
            return base.Channel.ListIemOPD(strENRowid);
        }
        
        public System.Data.DataTable ListIemIPD(int strENRowid) {
            return base.Channel.ListIemIPD(strENRowid);
        }
        
        public System.Data.DataTable GetCareproviderCode(string strUsrCode) {
            return base.Channel.GetCareproviderCode(strUsrCode);
        }
        
        public System.Data.DataTable getUser(string strUsrCode) {
            return base.Channel.getUser(strUsrCode);
        }
        
        public System.Data.DataTable GetTop5Diagnosis(string strHN) {
            return base.Channel.GetTop5Diagnosis(strHN);
        }
        
        public System.Data.DataTable GetDiagnosis(string HN, string DoctorUserID, string BeginDate, string EndDate, string EN) {
            return base.Channel.GetDiagnosis(HN, DoctorUserID, BeginDate, EndDate, EN);
        }
        
        public System.Data.DataTable GetDiagnosisByDate(string strHN, string strBeginDate, string strEndDate) {
            return base.Channel.GetDiagnosisByDate(strHN, strBeginDate, strEndDate);
        }
        
        public System.Data.DataTable GetMedicineByEn(string strHN, string strEn) {
            return base.Channel.GetMedicineByEn(strHN, strEn);
        }
        
        public System.Data.DataTable GetDiagnosisByEn(string strHN, string strEn) {
            return base.Channel.GetDiagnosisByEn(strHN, strEn);
        }
        
        public System.Data.DataTable GetDiagnosisByEnAll(string strHN, string strEn) {
            return base.Channel.GetDiagnosisByEnAll(strHN, strEn);
        }
        
        public System.Data.DataTable GetTop5Medicine(string strHN) {
            return base.Channel.GetTop5Medicine(strHN);
        }
        
        public System.Data.DataTable GetMedicineByDate(string strHN, string strBeginDate, string strEndDate) {
            return base.Channel.GetMedicineByDate(strHN, strBeginDate, strEndDate);
        }
        
        public System.Data.DataTable GetTop5NextAppointment(string strHN) {
            return base.Channel.GetTop5NextAppointment(strHN);
        }
        
        public System.Data.DataTable GetAppointmentByHN(string strHN, string isHPC) {
            return base.Channel.GetAppointmentByHN(strHN, isHPC);
        }
        
        public System.Data.DataTable GetCheckupLab(string strHn, string strFrom, string strTo) {
            return base.Channel.GetCheckupLab(strHn, strFrom, strTo);
        }
        
        public System.Data.DataTable GetXrayResultList_XrayResult(string PMINo, string OrdSttDateFrom, string OrdSttDateTo, string ADMRowId) {
            return base.Channel.GetXrayResultList_XrayResult(PMINo, OrdSttDateFrom, OrdSttDateTo, ADMRowId);
        }
        
        public System.Data.DataTable ListCurrentMedByEN(string strEN) {
            return base.Channel.ListCurrentMedByEN(strEN);
        }
        
        public System.Data.DataTable GetItemForThreeVisit(string strHn) {
            return base.Channel.GetItemForThreeVisit(strHn);
        }
        
        public System.Data.DataTable GetMedicineByHN(string strHN, string BeginDate, string EndDate) {
            return base.Channel.GetMedicineByHN(strHN, BeginDate, EndDate);
        }
        
        public System.Data.DataTable ListMed(string CodeOrDesc) {
            return base.Channel.ListMed(CodeOrDesc);
        }
        
        public System.Data.DataTable GetDiagForSave(string strHN, string strEn) {
            return base.Channel.GetDiagForSave(strHN, strEn);
        }
        
        public System.Data.DataTable getPTByHN(string strHN, string AdmDate) {
            return base.Channel.getPTByHN(strHN, AdmDate);
        }
        
        public System.Data.DataTable getManualHN(string strHN) {
            return base.Channel.getManualHN(strHN);
        }
        
        public System.Data.DataTable ListPayor() {
            return base.Channel.ListPayor();
        }
        
        public System.Data.DataTable getAllergen(string Input) {
            return base.Channel.getAllergen(Input);
        }
        
        public System.Data.DataTable GetOnWard(string Todate) {
            return base.Channel.GetOnWard(Todate);
        }
        
        public System.Data.DataTable GetPayorbyEN(string EN) {
            return base.Channel.GetPayorbyEN(EN);
        }
        
        public System.Data.DataTable getOnWardByDoc(string Todate, string DocCode) {
            return base.Channel.getOnWardByDoc(Todate, DocCode);
        }
        
        public System.Data.DataTable getPatientByEpiRowID(string EpiRowID) {
            return base.Channel.getPatientByEpiRowID(EpiRowID);
        }
        
        public System.Data.DataTable getORRequestOT(string RequestDate) {
            return base.Channel.getORRequestOT(RequestDate);
        }
        
        public System.Data.DataTable getORAnaestMethod(string CodeDesc) {
            return base.Channel.getORAnaestMethod(CodeDesc);
        }
        
        public System.Data.DataTable getORAnestTime(string AnaestNo, string EN) {
            return base.Channel.getORAnestTime(AnaestNo, EN);
        }
        
        public System.Data.DataTable getOrderByHnSubCat(string HN, string SubCatCode) {
            return base.Channel.getOrderByHnSubCat(HN, SubCatCode);
        }
        
        public System.Data.DataTable getOrderByEN(string EN) {
            return base.Channel.getOrderByEN(EN);
        }
        
        public System.Data.DataTable LogonTrakcare(string UserID, string Password) {
            return base.Channel.LogonTrakcare(UserID, Password);
        }
        
        public System.Data.DataTable GetVitalSignByHN(string HN) {
            return base.Channel.GetVitalSignByHN(HN);
        }
        
        public System.Data.DataTable getVitalSignByHN_EN(string HN, string EN) {
            return base.Channel.getVitalSignByHN_EN(HN, EN);
        }
        
        public System.Data.DataTable GetLastEN(string HN) {
            return base.Channel.GetLastEN(HN);
        }
        
        public System.Data.DataTable GetPTDemographic(string HN) {
            return base.Channel.GetPTDemographic(HN);
        }
        
        public System.Data.DataTable GetVaccineByHN(string strHN) {
            return base.Channel.GetVaccineByHN(strHN);
        }
        
        public System.Data.DataTable GetPharItem(string ARCIM_Code) {
            return base.Channel.GetPharItem(ARCIM_Code);
        }
        
        public System.Data.DataTable GetBrestPatientByHN(string HN) {
            return base.Channel.GetBrestPatientByHN(HN);
        }
        
        public System.Data.DataTable GetPTAppointment(string HPCSite, string AppDate) {
            return base.Channel.GetPTAppointment(HPCSite, AppDate);
        }
        
        public System.Data.DataTable GetPTArrived(string HPCSite, string AppDate) {
            return base.Channel.GetPTArrived(HPCSite, AppDate);
        }
        
        public System.Data.DataTable GetPTArrivedCheckUp(string HPCSite, string AppDate) {
            return base.Channel.GetPTArrivedCheckUp(HPCSite, AppDate);
        }
        
        public System.Data.DataTable GetPTArrivedCheckUpFilter(string HPCSite, string EN, string AppDate) {
            return base.Channel.GetPTArrivedCheckUpFilter(HPCSite, EN, AppDate);
        }
        
        public System.Data.DataTable GetPTOrderByLocDateHn(string HPCSite, string OrderDate, string HN) {
            return base.Channel.GetPTOrderByLocDateHn(HPCSite, OrderDate, HN);
        }
        
        public System.Data.DataTable GetAllOrderSet(string input) {
            return base.Channel.GetAllOrderSet(input);
        }
        
        public System.Data.DataTable GetAllOrderItem(string input) {
            return base.Channel.GetAllOrderItem(input);
        }
        
        public System.Data.DataTable GetAllICD10(string input) {
            return base.Channel.GetAllICD10(input);
        }
        
        public System.Data.DataTable GetAllICD9(string input) {
            return base.Channel.GetAllICD9(input);
        }
        
        public System.Data.DataTable GetPTPackage(int EN_RowId) {
            return base.Channel.GetPTPackage(EN_RowId);
        }
        
        public System.Data.DataTable GetAllergyByHN(string HN) {
            return base.Channel.GetAllergyByHN(HN);
        }
        
        public System.Data.DataTable GetAllAllergyByHN(string HN) {
            return base.Channel.GetAllAllergyByHN(HN);
        }
        
        public System.Data.DataTable GetAllAllergyByHN_NameDob(string HN, string name, string dob_yyyyMMdd) {
            return base.Channel.GetAllAllergyByHN_NameDob(HN, name, dob_yyyyMMdd);
        }
        
        public System.Data.DataTable GetItemByOrserSet(int OrderSetId) {
            return base.Channel.GetItemByOrserSet(OrderSetId);
        }
        
        public System.Data.DataTable GetLocationByType(string LocType) {
            return base.Channel.GetLocationByType(LocType);
        }
        
        public System.Data.DataTable GetQuestionnaireHPC(string HN) {
            return base.Channel.GetQuestionnaireHPC(HN);
        }
        
        public System.Data.DataTable GetCareprovider(string Input) {
            return base.Channel.GetCareprovider(Input);
        }
        
        public System.Data.DataTable GetORCareprovider(string Input) {
            return base.Channel.GetORCareprovider(Input);
        }
        
        public System.Data.DataTable GetORAnaestCareprovider(string Input) {
            return base.Channel.GetORAnaestCareprovider(Input);
        }
        
        public System.Data.DataTable getApptByHN(string HN, string Location, string ApptDate) {
            return base.Channel.getApptByHN(HN, Location, ApptDate);
        }
        
        public System.Data.DataTable ListCityArea(string input) {
            return base.Channel.ListCityArea(input);
        }
        
        public System.Data.DataTable ListCity(string input) {
            return base.Channel.ListCity(input);
        }
        
        public System.Data.DataTable ListProvince(string input) {
            return base.Channel.ListProvince(input);
        }
        
        public System.Data.DataTable ListAddress(string input) {
            return base.Channel.ListAddress(input);
        }
        
        public System.Data.DataTable GetOperationByHN(string input) {
            return base.Channel.GetOperationByHN(input);
        }
        
        public System.Data.DataTable GetMedicineByDoctor(string strHN, string strEn, string DocCode) {
            return base.Channel.GetMedicineByDoctor(strHN, strEn, DocCode);
        }
        
        public System.Data.DataTable GetOtherAddress(string HN) {
            return base.Channel.GetOtherAddress(HN);
        }
        
        public System.Data.DataTable GetDiagnosisByDoctor(string strHN, string strEn, string DocCode) {
            return base.Channel.GetDiagnosisByDoctor(strHN, strEn, DocCode);
        }
        
        public System.Data.DataTable ListPaymentAgreement(string input) {
            return base.Channel.ListPaymentAgreement(input);
        }
        
        public System.Data.DataTable ListPlan(string input) {
            return base.Channel.ListPlan(input);
        }
        
        public System.Data.DataTable GetXrayResult(string strHN, string BeginDate, string EndDate) {
            return base.Channel.GetXrayResult(strHN, BeginDate, EndDate);
        }
        
        public System.Data.DataTable GetPharDrugForm(string PHCD_Code) {
            return base.Channel.GetPharDrugForm(PHCD_Code);
        }
        
        public System.Data.DataTable GetAdmitHistory(string HN) {
            return base.Channel.GetAdmitHistory(HN);
        }
        
        public System.Data.DataTable GetProcedureByHN(string HN, string DateFrom, string DateTo) {
            return base.Channel.GetProcedureByHN(HN, DateFrom, DateTo);
        }
        
        public System.Data.DataTable GetContactPerson(string HN) {
            return base.Channel.GetContactPerson(HN);
        }
        
        public System.Data.DataTable GetDischargeDate(string EN) {
            return base.Channel.GetDischargeDate(EN);
        }
        
        public string GetManualLab(string strHn, string strFrom, string strTo) {
            return base.Channel.GetManualLab(strHn, strFrom, strTo);
        }
        
        public string findDiagnosis(string keyword) {
            return base.Channel.findDiagnosis(keyword);
        }
        
        public string findMedication(string keyword) {
            return base.Channel.findMedication(keyword);
        }
        
        public string GetDrug(string keyword) {
            return base.Channel.GetDrug(keyword);
        }
        
        public System.Data.DataTable GetEPIRowIDByEN(string EN) {
            return base.Channel.GetEPIRowIDByEN(EN);
        }
        
        public System.Data.DataTable GetPTImageByHN(string HN) {
            return base.Channel.GetPTImageByHN(HN);
        }
        
        public System.Data.DataTable GetBannerByHN(string HN) {
            return base.Channel.GetBannerByHN(HN);
        }
        
        public System.Data.DataTable Get4PathwayPTInfoByEN(string Admdate, string EN) {
            return base.Channel.Get4PathwayPTInfoByEN(Admdate, EN);
        }
        
        public System.Data.DataTable GetPTInfoByHN(string HN) {
            return base.Channel.GetPTInfoByHN(HN);
        }
        
        public System.Data.DataTable GetPTInfoByEN(string EN) {
            return base.Channel.GetPTInfoByEN(EN);
        }
        
        public System.Data.DataTable GetStartToEndEpisodeByEN(string EN) {
            return base.Channel.GetStartToEndEpisodeByEN(EN);
        }
        
        public System.Data.DataTable GetConsultLocationByEN(string EN) {
            return base.Channel.GetConsultLocationByEN(EN);
        }
        
        public System.Data.DataTable GetOTRequestDoneBySurgeryDate(string SurgeryDate) {
            return base.Channel.GetOTRequestDoneBySurgeryDate(SurgeryDate);
        }
        
        public System.Data.DataTable GetCurrentRoomByEN(string EN) {
            return base.Channel.GetCurrentRoomByEN(EN);
        }
        
        public System.Data.DataTable GetWardRoomBedMovementByEN(string EN) {
            return base.Channel.GetWardRoomBedMovementByEN(EN);
        }
        
        public System.Data.DataTable GetCurrentENByHN(string HN) {
            return base.Channel.GetCurrentENByHN(HN);
        }
        
        public System.Data.DataTable ListOperationByHN(string HN) {
            return base.Channel.ListOperationByHN(HN);
        }
        
        public System.Data.DataTable GetAdmissionAppointmentByDate(string date) {
            return base.Channel.GetAdmissionAppointmentByDate(date);
        }
        
        public System.Data.DataTable GetOrderItemByDesc(string Desc) {
            return base.Channel.GetOrderItemByDesc(Desc);
        }
        
        public System.Data.DataTable GetBillSubByDesc(string Desc) {
            return base.Channel.GetBillSubByDesc(Desc);
        }
        
        public System.Data.DataTable GetBillGroupByDesc(string Desc) {
            return base.Channel.GetBillGroupByDesc(Desc);
        }
        
        public System.Data.DataTable GetOrderSetOrderItemByDesc(string Desc) {
            return base.Channel.GetOrderSetOrderItemByDesc(Desc);
        }
        
        public System.Data.DataTable GetOrderDetailByOrderRowID(string RowID) {
            return base.Channel.GetOrderDetailByOrderRowID(RowID);
        }
        
        public System.Data.DataTable GetLabByHNLabCode(string HN, string LabCode, string LabSet, int Rank) {
            return base.Channel.GetLabByHNLabCode(HN, LabCode, LabSet, Rank);
        }
        
        public System.Data.DataTable GetPTArrivedIncaseFlatFileNotGen(string ArrDate) {
            return base.Channel.GetPTArrivedIncaseFlatFileNotGen(ArrDate);
        }
        
        public System.Data.DataTable GetStockItemFromTrak(string strKeyWord) {
            return base.Channel.GetStockItemFromTrak(strKeyWord);
        }
        
        public System.Data.DataTable GetLogonAD(string username, string password) {
            return base.Channel.GetLogonAD(username, password);
        }
        
        public System.Data.DataTable GetAuditEPR(string hn, string dateFrom, string dateTo) {
            return base.Channel.GetAuditEPR(hn, dateFrom, dateTo);
        }
        
        public System.Data.DataTable GetAuditDocView(string hn, string dateFrom, string dateTo) {
            return base.Channel.GetAuditDocView(hn, dateFrom, dateTo);
        }
        
        public System.Data.DataTable GetORSEquipmentImplant() {
            return base.Channel.GetORSEquipmentImplant();
        }
        
        public System.Data.DataTable GetBDMSNexEntel_Data(string hn) {
            return base.Channel.GetBDMSNexEntel_Data(hn);
        }
        
        public System.Data.DataTable GetPatientAdmissionByDate(string Dateyyy_mm_dd) {
            return base.Channel.GetPatientAdmissionByDate(Dateyyy_mm_dd);
        }
        
        public System.Data.DataTable GetOrderAdmissionByDate(string Dateyyy_mm_dd) {
            return base.Channel.GetOrderAdmissionByDate(Dateyyy_mm_dd);
        }
        
        public System.Data.DataTable GetDischargeInfoByFinalDate(string FinalDateyyy_mm_dd) {
            return base.Channel.GetDischargeInfoByFinalDate(FinalDateyyy_mm_dd);
        }
        
        public System.Data.DataTable GetConsultMedicine(string Dateyyy_mm_dd, string OrderCode) {
            return base.Channel.GetConsultMedicine(Dateyyy_mm_dd, OrderCode);
        }
        
        public System.Data.DataTable GetPhamacyReview(string PrescNo) {
            return base.Channel.GetPhamacyReview(PrescNo);
        }
    }
}
