//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckupWebService.WS_SendToDocscan {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_SendToDocscan.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Parameter 'image' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveToDocscan", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CheckupWebService.WS_SendToDocscan.SaveToDocscanResponse SaveToDocscan(CheckupWebService.WS_SendToDocscan.SaveToDocscanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveToDocscanFromFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string SaveToDocscanFromFile(string pathimage, string hn, string en, string page, string doctorcode, string locationcode, string documentcode, string userid, string programid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getVisitdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getVisitdate(string hn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDoctor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getDoctor(string hn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getDocument(string hn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDocumentlistByEN_groupdocument_fixdoctor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getDocumentlistByEN_groupdocument_fixdoctor(string hn, string doctor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDocumentlistByENDate_groupdocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getDocumentlistByENDate_groupdocument(string hn, string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDocumentlistByEN_and_caregiver", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable getDocumentlistByEN_and_caregiver(string hn, string en, string doctor, string grp, string subgrp);
        
        // CODEGEN: Parameter 'getImageResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getImage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CheckupWebService.WS_SendToDocscan.getImageResponse getImage(CheckupWebService.WS_SendToDocscan.getImageRequest request);
        
        // CODEGEN: Parameter 'getImagethumbResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getImagethumb", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CheckupWebService.WS_SendToDocscan.getImagethumbResponse getImagethumb(CheckupWebService.WS_SendToDocscan.getImagethumbRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveToDocscan", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveToDocscanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] image;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string hn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string en;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string page;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string doctorcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string locationcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string documentcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string userid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string programid;
        
        public SaveToDocscanRequest() {
        }
        
        public SaveToDocscanRequest(byte[] image, string hn, string en, string page, string doctorcode, string locationcode, string documentcode, string userid, string programid) {
            this.image = image;
            this.hn = hn;
            this.en = en;
            this.page = page;
            this.doctorcode = doctorcode;
            this.locationcode = locationcode;
            this.documentcode = documentcode;
            this.userid = userid;
            this.programid = programid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveToDocscanResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveToDocscanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SaveToDocscanResult;
        
        public SaveToDocscanResponse() {
        }
        
        public SaveToDocscanResponse(string SaveToDocscanResult) {
            this.SaveToDocscanResult = SaveToDocscanResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getImage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string hn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string en;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string itemno;
        
        public getImageRequest() {
        }
        
        public getImageRequest(string hn, string en, string itemno) {
            this.hn = hn;
            this.en = en;
            this.itemno = itemno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getImageResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getImageResult;
        
        public getImageResponse() {
        }
        
        public getImageResponse(byte[] getImageResult) {
            this.getImageResult = getImageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getImagethumb", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getImagethumbRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string hn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string en;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string itemno;
        
        public getImagethumbRequest() {
        }
        
        public getImagethumbRequest(string hn, string en, string itemno) {
            this.hn = hn;
            this.en = en;
            this.itemno = itemno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getImagethumbResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getImagethumbResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] getImagethumbResult;
        
        public getImagethumbResponse() {
        }
        
        public getImagethumbResponse(byte[] getImagethumbResult) {
            this.getImagethumbResult = getImagethumbResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : CheckupWebService.WS_SendToDocscan.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<CheckupWebService.WS_SendToDocscan.ServiceSoap>, CheckupWebService.WS_SendToDocscan.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CheckupWebService.WS_SendToDocscan.SaveToDocscanResponse CheckupWebService.WS_SendToDocscan.ServiceSoap.SaveToDocscan(CheckupWebService.WS_SendToDocscan.SaveToDocscanRequest request) {
            return base.Channel.SaveToDocscan(request);
        }
        
        public string SaveToDocscan(byte[] image, string hn, string en, string page, string doctorcode, string locationcode, string documentcode, string userid, string programid) {
            CheckupWebService.WS_SendToDocscan.SaveToDocscanRequest inValue = new CheckupWebService.WS_SendToDocscan.SaveToDocscanRequest();
            inValue.image = image;
            inValue.hn = hn;
            inValue.en = en;
            inValue.page = page;
            inValue.doctorcode = doctorcode;
            inValue.locationcode = locationcode;
            inValue.documentcode = documentcode;
            inValue.userid = userid;
            inValue.programid = programid;
            CheckupWebService.WS_SendToDocscan.SaveToDocscanResponse retVal = ((CheckupWebService.WS_SendToDocscan.ServiceSoap)(this)).SaveToDocscan(inValue);
            return retVal.SaveToDocscanResult;
        }
        
        public string SaveToDocscanFromFile(string pathimage, string hn, string en, string page, string doctorcode, string locationcode, string documentcode, string userid, string programid) {
            return base.Channel.SaveToDocscanFromFile(pathimage, hn, en, page, doctorcode, locationcode, documentcode, userid, programid);
        }
        
        public System.Data.DataTable getVisitdate(string hn) {
            return base.Channel.getVisitdate(hn);
        }
        
        public System.Data.DataTable getDoctor(string hn) {
            return base.Channel.getDoctor(hn);
        }
        
        public System.Data.DataTable getDocument(string hn) {
            return base.Channel.getDocument(hn);
        }
        
        public System.Data.DataTable getDocumentlistByEN_groupdocument_fixdoctor(string hn, string doctor) {
            return base.Channel.getDocumentlistByEN_groupdocument_fixdoctor(hn, doctor);
        }
        
        public System.Data.DataTable getDocumentlistByENDate_groupdocument(string hn, string date) {
            return base.Channel.getDocumentlistByENDate_groupdocument(hn, date);
        }
        
        public System.Data.DataTable getDocumentlistByEN_and_caregiver(string hn, string en, string doctor, string grp, string subgrp) {
            return base.Channel.getDocumentlistByEN_and_caregiver(hn, en, doctor, grp, subgrp);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CheckupWebService.WS_SendToDocscan.getImageResponse CheckupWebService.WS_SendToDocscan.ServiceSoap.getImage(CheckupWebService.WS_SendToDocscan.getImageRequest request) {
            return base.Channel.getImage(request);
        }
        
        public byte[] getImage(string hn, string en, string itemno) {
            CheckupWebService.WS_SendToDocscan.getImageRequest inValue = new CheckupWebService.WS_SendToDocscan.getImageRequest();
            inValue.hn = hn;
            inValue.en = en;
            inValue.itemno = itemno;
            CheckupWebService.WS_SendToDocscan.getImageResponse retVal = ((CheckupWebService.WS_SendToDocscan.ServiceSoap)(this)).getImage(inValue);
            return retVal.getImageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CheckupWebService.WS_SendToDocscan.getImagethumbResponse CheckupWebService.WS_SendToDocscan.ServiceSoap.getImagethumb(CheckupWebService.WS_SendToDocscan.getImagethumbRequest request) {
            return base.Channel.getImagethumb(request);
        }
        
        public byte[] getImagethumb(string hn, string en, string itemno) {
            CheckupWebService.WS_SendToDocscan.getImagethumbRequest inValue = new CheckupWebService.WS_SendToDocscan.getImagethumbRequest();
            inValue.hn = hn;
            inValue.en = en;
            inValue.itemno = itemno;
            CheckupWebService.WS_SendToDocscan.getImagethumbResponse retVal = ((CheckupWebService.WS_SendToDocscan.ServiceSoap)(this)).getImagethumb(inValue);
            return retVal.getImagethumbResult;
        }
    }
}
